### ISSUE TITLE
该插件如何查看编译Enum时编译器编译增加的东西？？

### ISSUE THREAD

**Issue by wezhyn** [mrdear/asm-bytecode-intellij#1]
还有什么String 这些？？

**Comment by mrdear** [comment]
@wezhyn 这个插件只是对CFR的包装，要看到具体反编译的内容需要自己在IDEA-> Setting -> ASM Bytecode plugin中加参数，比如查看enum加`--sugarenums false `参数，查看字符串拼接加`--stringbuilder false`

**Comment by wezhyn** [comment]
> @wezhyn 这个插件只是对CFR的包装，要看到具体反编译的内容需要自己在IDEA-> Setting -> ASM Bytecode plugin中加参数，比如查看enum加`--sugarenums false`参数，查看字符串拼接加`--stringbuilder false`

十分感谢你的帮助，我之前一直不知道，插件还能自己添加参数
